version: 2.1
jobs:
  this-will-never-run:
    docker:
      - image: cibuilds/github:latest
    steps:
      - run: ls .

workflows:
  do-not-run-ci-for-master:
    jobs:
      - this-will-never-run:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore: /.*/
