version: 2.1

jobs:
  getcode:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Get code
          shell: /bin/bash
          command: |
            #git clone --depth 1 --branch $CIRCLE_BRANCH  $CIRCLE_REPOSITORY_URL
            pwd
            ls
            rm -Rf .git
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    parameters:
      model:
        type: string
      release_dir:
        type: string
    docker:
      - image: ivano/asuswrt-merlin-toolchains-custom:2023-09-29
        environment:
          PROJECT_DIR: "/home/docker/project"
          CHANGELOG_FILE: "/tmp/CHANGELOG"
          MODEL: << parameters.model >>
          RELEASE_DIR: << parameters.release_dir >>
          LD_LIBRARY_PATH: "$LD_LIBRARY:~/am-toolchains/brcm-arm-sdk/hndtools-arm-linux-2.6.36-uclibc-4.5.3/lib"
          PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/toolchains/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin:/opt/toolchains/crosstools-aarch64-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin:/opt/toolchains/crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin:/opt/toolchains/crosstools-aarch64-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin:/opt/brcm-arm/bin:/opt/toolchains/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin:/opt/toolchains/crosstools-aarch64-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin:/opt/toolchains/crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin:/opt/toolchains/crosstools-aarch64-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin:/opt/brcm-arm/bin"
          TERM: "xterm-256color"
    resource_class: large
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Set Version from TAG
          shell: /bin/bash
          command: |
            if [ -z "${CIRCLE_TAG}" ]; then
              echo "Nothing to do. Not a release."
            else
              MAJOR_VER=$(echo "${CIRCLE_TAG}" | sed -E 's/([0-9.]*)[_-]?(.*)/\1/')
              MINOR_VER=$(echo "${CIRCLE_TAG}" | sed -E 's/([0-9.]*)[_-]?(.*)/\2/')
              sed -i "s/SERIALNO=.*/SERIALNO=${MAJOR_VER}/g" release/src-rt/version.conf
              sed -i "s/EXTENDNO=.*/EXTENDNO=${MINOR_VER}/g" release/src-rt/version.conf
            fi
      - run:
          name: Generate changelog
          command: |
            python tools/get-last-notes.py > "${CHANGELOG_FILE}"
            cat "${CHANGELOG_FILE}"
      - run:
          name: Build firmware
          shell: /bin/bash
          no_output_timeout: 120m
          command: |
            export MERLINUPDATE=y
            cd ${PROJECT_DIR}/release/${RELEASE_DIR}
            echo "----- Files in dir: $(pwd) -----"
            ls -alh
            echo "----- ENV VARS -----"
            source  ~/.profile
            env
            echo "----- SETTING UP SECRET FILES -----"
            if [[ ${MODEL} == "dsl-ac68u" ]]; then
              echo $BWDPI_KEYS_DSLAC68U | base64 -d > /tmp/keys.tgz
              tar xzf /tmp/keys.tgz --no-same-owner -C ${PROJECT_DIR}/release/${RELEASE_DIR}/router/bwdpi_source/prebuild/DSL-AC68U
            fi
            echo "----- BUILD -----"
            make ${MODEL} | tee "/tmp/build.log"
            echo "------ DONE -----"
            ls ${PROJECT_DIR}/release/${RELEASE_DIR}/image/
      - run:
          name: Prepare workspace
          shell: /bin/bash
          command: |
            export IMAGE_PATH=${PROJECT_DIR}/release/${RELEASE_DIR}/image/
            mkdir -p workspace/release/
            if [[ ${MODEL} == "dsl-ac68u" ]]; then
              mv "${IMAGE_PATH}/DSL-AC68U_${CIRCLE_TAG}.trx" "${IMAGE_PATH}/DSL-AC68U_${CIRCLE_TAG}_NO-DSL-FIRMWARE.trx"
              cp ${IMAGE_PATH}/*.trx workspace/release/
              cp ${IMAGE_PATH}/DSL*DSL*.md5 workspace/release/ || :
            else
              cp ${IMAGE_PATH}/*_cferom_puresqubi.md5 workspace/release
              cp ${IMAGE_PATH}/*_cferom_puresqubi.w   workspace/release || :
            fi
            cp /tmp/build.log workspace/release/${MODEL}-build.log
            if [ -z "${CIRCLE_TAG}" ]; then
              echo "No CHANGELOG to copy. Not a release build."
            else
              # Changelogs are the same for each models since we are building from the same branch. We do use only the one generated by DSL-AC68U for now.
              if [[ ${MODEL} == "dsl-ac68u" ]]; then
                cp "${CHANGELOG_FILE}" workspace/release
              fi
            fi
      - store_artifacts:
          path: workspace/release
      - persist_to_workspace:
          root: workspace
          paths:
            - release
  publish-manifest-and-notes:
    docker:
      - image: cibuilds/github:latest
    steps:
      - attach_workspace:
          at: workspace
      - add_ssh_keys:
          fingerprints:
            - "a8:9c:28:88:e9:d8:0e:da:a7:6e:2b:7b:e5:e4:f6:e3"
      - run:
          name: "Publish manifest and release note for the current build"
          command: |
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email "bot@ion.org"
            git config --global user.name "Circle CI BOT"
            git config --global push.default simple
            git clone -b master --single-branch git@github.com:oivano/asuswrt-merlin.ng.git
            cd asuswrt-merlin.ng
            UPDATE_DIR=updates
            MAJOR_VER=$(echo "${CIRCLE_TAG}" | sed -E 's/([0-9.]*)[_-]?(.*)/\1/')
            MINOR_VER=$(echo "${CIRCLE_TAG}" | sed -E 's/([0-9.]*)[_-]?(.*)/\2/')
            RELEASE_NOTE_FILE=$(echo "${MAJOR_VER}_${MINOR_VER}_note.txt" | sed "s/\./_/")
            echo "Generating manifest file..."
            echo "DSL-AC68U#FW${MAJOR_VER}#EXT${MINOR_VER}#BETAFW0#BETAEXT0#" > ${UPDATE_DIR}/manifest.txt
            cp $HOME/project/workspace/release/CHANGELOG ${UPDATE_DIR}/"${RELEASE_NOTE_FILE}"
            echo "Uploading to github manifest and ${RELEASE_NOTE_FILE}"
            git add ${UPDATE_DIR}
            git commit -m "Updating Notes and manifest to version:${MAJOR_VER} ${MINOR_VER} [ci skip]" -a
            git push origin
  publish-github-release:
    docker:
      - image: cibuilds/github:latest
    steps:
      - attach_workspace:
          at: workspace
      - run: ls workspace/release
      - run:
          name: "Publish Release on Github"
          command: |
            echo "Uploading release..."
            RELEASE_TITLE="Stable: ${CIRCLE_TAG}"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete -n "${RELEASE_TITLE}" -b "$(cat workspace/release/CHANGELOG | head -n 50)" ${CIRCLE_TAG} workspace/release/
  publish-github-ci-pre-release:
    docker:
      - image: cibuilds/github:latest
    steps:
      - attach_workspace:
          at: workspace
      - run: ls workspace/release
      - run:
          name: "Publish CI pre-release on Github"
          command: |
            echo "Uploading CI pre-release..."
            RELEASE_TITLE="Unstable: ${CIRCLE_TAG}"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n "${RELEASE_TITLE}" -b "$(cat workspace/release/CHANGELOG | head -n 50)" -delete -prerelease ${CIRCLE_TAG} workspace/release/

workflows:
  version: 2.1
  build_and_release:
    jobs:
      - getcode:
          filters:
            tags:
              only: /.*/
      - build:
          name: "build_dsl-ac68u"
          model: "dsl-ac68u"
          release_dir: "src-rt-6.x.4708"
          requires:
            - getcode
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - master
                - mainline
      - request-testing:
          type: approval
          filters:
            tags:
              only: /[0-9]+.*ion+/
            branches:
              ignore: /.*/
          requires:
            - build_dsl-ac68u
      - publish-manifest-and-notes:
          filters:
            tags:
              only: /[0-9]+.*ion+/
            branches:
              ignore: /.*/
          requires:
            - request-testing
      - publish-github-release:
          filters:
            tags:
              only: /[0-9]+.*ion+/
            branches:
              ignore: /.*/
          requires:
            - publish-manifest-and-notes
      - publish-github-ci-pre-release:
          filters:
            tags:
              only:
               - /ion-snapshot-.*/
               - /[0-9]+.*ion_beta[0-9]+/
               - /[0-9]+.*ion_alpha[0-9]+/
            branches:
              ignore: /.*/
          requires:
            - build_dsl-ac68u
notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/fe1ed0d17eff95999455
