/*
 * FRR (Free Range Routing) service control
 * Copyright (C) 2026 AsusWRT-Merlin
 */

#include "rc.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <signal.h>
#include <sys/stat.h>

#define FRR_RUN_DIR		"/var/run/frr"
#define FRR_CONFIG_DIR		"/etc"
#define FRR_SCRIPT		"/usr/sbin/frr"
#define FRR_DAEMONS		"/etc/daemons"
#define FRR_CONF		"/etc/frr.conf"
#define FRR_VTYSH_CONF		"/etc/vtysh.conf"

/* Check if FRR is enabled in NVRAM */
static int is_frr_enabled(void)
{
	/* Check routing mode and FRR enable flag */
	if (!is_routing_enabled()) {
		_dprintf("FRR: Routing is not enabled\n");
		return 0;
	}
	
	return nvram_match("frr_enable", "1");
}

/* Create necessary directories */
static void frr_create_dirs(void)
{
	mkdir_if_none(FRR_RUN_DIR);
	mkdir_if_none(FRR_CONFIG_DIR);
	
	/* Set permissions */
	chmod(FRR_RUN_DIR, 0755);
	chmod(FRR_CONFIG_DIR, 0755);
}

/* Write default configuration files if they don't exist */
static void frr_write_default_config(void)
{
	FILE *fp;
	struct stat st;
	char *frr_passwd, *frr_enpasswd;
	char *hostname;
	
	/* Get passwords from NVRAM (compatible with old zebra_passwd) */
	frr_passwd = nvram_safe_get("frr_passwd");
	if (!*frr_passwd)
		frr_passwd = nvram_safe_get("zebra_passwd"); /* Fallback for Quagga migration */
	if (!*frr_passwd)
		frr_passwd = "zebra"; /* Default */
	
	frr_enpasswd = nvram_safe_get("frr_enpasswd");
	if (!*frr_enpasswd)
		frr_enpasswd = nvram_safe_get("zebra_enpasswd"); /* Fallback for Quagga migration */
	if (!*frr_enpasswd)
		frr_enpasswd = "zebra"; /* Default */
	
	hostname = nvram_safe_get("productid");
	if (!*hostname)
		hostname = "FRR";

#ifdef RTCONFIG_NVRAM_ENCRYPT
	/* Decrypt passwords if encryption is enabled */
	int declen = strlen(frr_passwd);
	char *dec_passwd = NULL;
	if (declen > 0) {
		dec_passwd = malloc(declen + 1);
		if (dec_passwd) {
			memset(dec_passwd, 0, declen + 1);
			if (pw_dec(frr_passwd, dec_passwd, declen, 1) > 0)
				frr_passwd = dec_passwd;
		}
	}
	
	int declen2 = strlen(frr_enpasswd);
	char *dec_enpasswd = NULL;
	if (declen2 > 0) {
		dec_enpasswd = malloc(declen2 + 1);
		if (dec_enpasswd) {
			memset(dec_enpasswd, 0, declen2 + 1);
			if (pw_dec(frr_enpasswd, dec_enpasswd, declen2, 1) > 0)
				frr_enpasswd = dec_enpasswd;
		}
	}
#endif
	
	/* Create daemons file if missing */
	if (stat(FRR_DAEMONS, &st) != 0) {
		fp = fopen(FRR_DAEMONS, "w");
		if (fp) {
			fprintf(fp, "# FRR daemons configuration\n");
			fprintf(fp, "# Generated by AsusWRT\n");
			fprintf(fp, "#\n");
			fprintf(fp, "zebra=yes\n");
			fprintf(fp, "bgpd=%s\n", nvram_match("frr_bgp_enable", "1") ? "yes" : "no");
			fprintf(fp, "ospfd=%s\n", nvram_match("frr_ospf_enable", "1") ? "yes" : "no");
			fprintf(fp, "staticd=yes\n");
			fprintf(fp, "bfdd=%s\n", nvram_match("frr_bfd_enable", "1") ? "yes" : "no");
			fprintf(fp, "#\n");
			fprintf(fp, "vtysh_enable=yes\n");
			fprintf(fp, "zebra_options=\" -s 90000000 --daemon -A 127.0.0.1\"\n");
			fprintf(fp, "bgpd_options=\" --daemon -A 127.0.0.1\"\n");
			fprintf(fp, "ospfd_options=\" --daemon -A 127.0.0.1\"\n");
			fprintf(fp, "staticd_options=\" --daemon -A 127.0.0.1\"\n");
			fprintf(fp, "bfdd_options=\" --daemon -A 127.0.0.1\"\n");
			
			/* Support for custom config additions */
			append_custom_config("frr_daemons", fp);
			fclose(fp);
			
			/* Allow custom config replacement */
			use_custom_config("frr_daemons", FRR_DAEMONS);
			run_postconf("frr_daemons", FRR_DAEMONS);
			
			chmod(FRR_DAEMONS, 0644);
		}
	}
	
	/* Create frr.conf if missing or regenerate on demand */
	if (stat(FRR_CONF, &st) != 0 || nvram_match("frr_force_regen", "1")) {
		fp = fopen(FRR_CONF, "w");
		if (fp) {
			char *lan_ip, *wan_if;
			char *bgp_as, *bgp_neighbor, *bgp_neighbor_as;
			char *ospf_area, *ospf_networks;
			
			lan_ip = nvram_safe_get("lan_ipaddr");
			wan_if = get_wan_ifname(wan_primary_ifunit());
			
			fprintf(fp, "!\n");
			fprintf(fp, "! FRR configuration\n");
			fprintf(fp, "! Generated by AsusWRT for compiled daemons:\n");
			fprintf(fp, "! zebra, bgpd, ospfd, staticd, bfdd\n");
			fprintf(fp, "!\n");
			fprintf(fp, "frr version 7.5.1\n");
			fprintf(fp, "frr defaults traditional\n");
			fprintf(fp, "hostname %s\n", hostname);
			fprintf(fp, "password %s\n", frr_passwd);
			fprintf(fp, "enable password %s\n", frr_enpasswd);
			fprintf(fp, "!\n");
			fprintf(fp, "log syslog informational\n");
			fprintf(fp, "!\n");
			fprintf(fp, "service integrated-vtysh-config\n");
			fprintf(fp, "!\n");
			
			/* === ZEBRA Configuration (always enabled) === */
			fprintf(fp, "! Zebra routing manager configuration\n");
			fprintf(fp, "! Manages kernel routing table and redistributes routes\n");
			fprintf(fp, "!\n");
			
			/* === STATIC Routes Configuration (staticd - always enabled) === */
			fprintf(fp, "! Static routes configuration\n");
			fprintf(fp, "! Add custom static routes via JFFS configs\n");
			fprintf(fp, "!\n");
			
			/* === BGP Configuration === */
			if (nvram_match("frr_bgp_enable", "1")) {
				bgp_as = nvram_safe_get("frr_bgp_as");
				bgp_neighbor = nvram_safe_get("frr_bgp_neighbor");
				bgp_neighbor_as = nvram_safe_get("frr_bgp_neighbor_as");
				
				if (*bgp_as) {
					fprintf(fp, "! BGP (Border Gateway Protocol) Configuration\n");
					fprintf(fp, "router bgp %s\n", bgp_as);
					fprintf(fp, " bgp router-id %s\n", lan_ip);
					fprintf(fp, " bgp log-neighbor-changes\n");
					
					/* BGP neighbor configuration */
					if (*bgp_neighbor && *bgp_neighbor_as) {
						fprintf(fp, " !\n");
						fprintf(fp, " neighbor %s remote-as %s\n", bgp_neighbor, bgp_neighbor_as);
						fprintf(fp, " neighbor %s password %s\n", bgp_neighbor, frr_passwd);
						fprintf(fp, " !\n");
						fprintf(fp, " address-family ipv4 unicast\n");
						fprintf(fp, "  network %s/24\n", lan_ip);
						fprintf(fp, "  neighbor %s activate\n", bgp_neighbor);
						fprintf(fp, " exit-address-family\n");
					}
					
					fprintf(fp, "!\n");
				}
			}
			
			/* === OSPF Configuration === */
			if (nvram_match("frr_ospf_enable", "1")) {
				ospf_area = nvram_safe_get("frr_ospf_area");
				ospf_networks = nvram_safe_get("frr_ospf_networks");
				
				if (!*ospf_area)
					ospf_area = "0"; /* Default backbone area */
				
				fprintf(fp, "! OSPF (Open Shortest Path First) Configuration\n");
				fprintf(fp, "router ospf\n");
				fprintf(fp, " ospf router-id %s\n", lan_ip);
				fprintf(fp, " log-adjacency-changes\n");
				fprintf(fp, " !\n");
				
				/* Network statements */
				if (*ospf_networks) {
					/* User-defined networks from NVRAM */
					fprintf(fp, " ! Custom networks from NVRAM\n");
					fprintf(fp, " ! Set frr_ospf_networks to networks separated by spaces\n");
					fprintf(fp, " ! Example: nvram set frr_ospf_networks=\"192.168.1.0/24 10.0.0.0/8\"\n");
					/* Networks are added via custom config or postconf */
				} else {
					/* Default: advertise all connected networks */
					fprintf(fp, " network 0.0.0.0/0 area %s\n", ospf_area);
				}
				
				fprintf(fp, " !\n");
				fprintf(fp, " ! Passive interfaces (don't send OSPF hello packets)\n");
#if !defined(BLUECAVE)
				fprintf(fp, " passive-interface vlan2\n");
				fprintf(fp, " passive-interface vlan3\n");
#else
				fprintf(fp, " passive-interface eth1.2\n");
				fprintf(fp, " passive-interface eth1.3\n");
#endif
				/* Add WAN interface as passive if exists */
				if (wan_if && *wan_if) {
					fprintf(fp, " passive-interface %s\n", wan_if);
				}
				
				fprintf(fp, "!\n");
			}
			
			/* === BFD Configuration === */
			if (nvram_match("frr_bfd_enable", "1")) {
				fprintf(fp, "! BFD (Bidirectional Forwarding Detection) Configuration\n");
				fprintf(fp, "! Provides fast failure detection for routing protocols\n");
				fprintf(fp, "bfd\n");
				fprintf(fp, " !\n");
				fprintf(fp, " ! BFD peers configured per protocol\n");
				fprintf(fp, " ! Example in BGP: neighbor <ip> bfd\n");
				fprintf(fp, " ! Example in OSPF: ip ospf bfd\n");
				fprintf(fp, "!\n");
			}
			
			/* === Access Control === */
			fprintf(fp, "! Access control for vty (telnet/ssh) connections\n");
			fprintf(fp, "access-list vty permit 127.0.0.0/8\n");
			
			/* Allow LAN access if configured */
			if (nvram_match("frr_allow_lan", "1")) {
				char *lan_netmask = nvram_safe_get("lan_netmask");
				if (*lan_ip && *lan_netmask) {
					fprintf(fp, "access-list vty permit %s/%s\n", lan_ip, lan_netmask);
				}
			}
			
			fprintf(fp, "access-list vty deny any\n");
			fprintf(fp, "!\n");
			fprintf(fp, "line vty\n");
			fprintf(fp, " access-class vty\n");
			fprintf(fp, " exec-timeout 0 0\n");
			fprintf(fp, "!\n");
			
			/* === Per-daemon custom configs === */
			fprintf(fp, "! Custom configurations\n");
			fprintf(fp, "! Add custom FRR commands via JFFS:\n");
			fprintf(fp, "! /jffs/configs/frr.conf.add\n");
			fprintf(fp, "!\n");
			
			/* Support for custom config additions */
			append_custom_config("frr.conf", fp);
			fclose(fp);
			
			/* Allow custom config replacement */
			use_custom_config("frr.conf", FRR_CONF);
			run_postconf("frr.conf", FRR_CONF);
			
			chmod(FRR_CONF, 0644);
		}
		nvram_unset("frr_force_regen");
	}
	
	/* Create vtysh.conf if missing */
	if (stat(FRR_VTYSH_CONF, &st) != 0) {
		fp = fopen(FRR_VTYSH_CONF, "w");
		if (fp) {
			fprintf(fp, "!\n");
			fprintf(fp, "service integrated-vtysh-config\n");
			fprintf(fp, "!\n");
			fclose(fp);
			chmod(FRR_VTYSH_CONF, 0644);
		}
	}

#ifdef RTCONFIG_NVRAM_ENCRYPT
	/* Free decrypted passwords */
	if (dec_passwd) free(dec_passwd);
	if (dec_enpasswd) free(dec_enpasswd);
#endif
}

void start_frr(void)
{
	if (!is_frr_enabled()) {
		_dprintf("FRR is not enabled\n");
		return;
	}
	
	/* Don't start if already running */
	if (pidof("watchfrr") > 0) {
		_dprintf("FRR watchfrr already running\n");
		return;
	}
	
	_dprintf("Starting FRR routing services...\n");
	
	/* Create directories and default configs */
	frr_create_dirs();
	frr_write_default_config();
	
	/* Start FRR using the init script */
	if (f_exists(FRR_SCRIPT)) {
		_dprintf("Executing: %s start\n", FRR_SCRIPT);
		eval(FRR_SCRIPT, "start");
	} else {
		logmessage("FRR", "Init script not found: %s", FRR_SCRIPT);
		_dprintf("FRR init script not found: %s\n", FRR_SCRIPT);
		return;
	}
	
	_dprintf("FRR started\n");
}

void stop_frr(void)
{
	_dprintf("Stopping FRR routing services...\n");
	
	/* Stop FRR using the init script */
	eval(FRR_SCRIPT, "stop");
	
	_dprintf("FRR stopped\n");
}

void restart_frr(void)
{
	stop_frr();
	sleep(2);
	start_frr();
}
