#!/bin/sh

log_success_msg() {
        echo "$@"
}
log_warning_msg() {
        echo "$@" >&2
}
log_failure_msg() {
        echo "$@" >&2
}

# "/usr/sbin/frrinit.sh start somenamespace"
FRR_PATHSPACE="$2"
self="`dirname $0`"
if [ -r "$self/frrcommon.sh" ]; then
	. "$self/frrcommon.sh"
else
	. "/usr/sbin/frrcommon.sh"
fi


start() {
	daemon_list daemons
	watchfrr_options="$watchfrr_options $daemons"
	daemon_start watchfrr
}
stop() {
	stop_watchfrr_first || exit ${still_running:-1}
	all_stop --reallyall
	exit ${still_running:-0}
}

restart() {
	stop_watchfrr_first || exit ${still_running:-1}
	all_stop --reallyall

	daemon_list daemons
	watchfrr_options="$watchfrr_options $daemons"
	daemon_start watchfrr
}

status() {
	fail=0
	print_status watchfrr || fail=1
	all_status || fail=1
	exit $fail
}

reload() {
	if [ ! -x "$RELOAD_SCRIPT" ]; then
		log_failure_msg "The frr-pythontools package is required for reload functionality."
		exit 1
	fi

	# restart watchfrr to pick up added daemons.
	# NB: This will NOT cause the other daemons to be restarted.
	daemon_list daemons
	watchfrr_options="$watchfrr_options $daemons"
	daemon_stop watchfrr && \
		daemon_start watchfrr

	NEW_CONFIG_FILE="${2:-$C_PATH/frr.conf}"
	[ ! -r $NEW_CONFIG_FILE ] && log_failure_msg "Unable to read new configuration file $NEW_CONFIG_FILE" && exit 1
	"$RELOAD_SCRIPT" --reload "$NEW_CONFIG_FILE"
	exit $?
}

try_service_action() {
	local svc="$1"

	if [ -x "/sbin/service" ]; then
		/sbin/service "$svc"
		return $?
	fi

	if command -v service >/dev/null 2>&1; then
		service "$svc"
		return $?
	fi

	return 127
}

case "$1" in
start)
	try_service_action start_frr || start
	;;
stop)
	try_service_action stop_frr || stop
	;;
restart|force-reload)
	try_service_action restart_frr || restart
	;;
status)
	status
	;;
reload)
	reload
	;;
*)
	log_failure_msg "Unknown command: $1"
	exit 1
	;;
esac

