#!/bin/bash
#set -e

# DSL-AC68U
# Run this script after having reviewed the merge

BUILD_NAME=$1
REPO=.
echo "*** Adding files to GIT after a GPL Merge..."

if [ "$BUILD_NAME" == "DSL-AC68U" ]
then
    git add -f $REPO/release/src/router/infosvr/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src-rt-6.x.4708/wl/exe/prebuilt/DSL-AC68U/*
    git add -f $REPO/release/src/router/bwdpi_source/asus_sql/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/bwdpi_source/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/cfg_mnt/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/dblog/daemon/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/emf_arm/*
    git add -f $REPO/release/src/router/et_arm/prebuilt/*
    git add -f $REPO/release/src/router/httpd/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/libletsencrypt/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/lighttpd-1.4.39/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/networkmap/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/nt_center/actMail/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/nt_center/lib/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/nt_center/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/rc/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/sambaclient/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/shared/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/sw-hw-auth/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/wb/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/wl_arm/prebuilt/DSL-AC68U/*
    git add -f $REPO/release/src/router/wlceventd/prebuilt/DSL-AC68U/*
    git add -f $REPO/release/src/router/wlconf_arm/prebuilt/*
    git add -f $REPO/release/src/router/wps_arm/*
    git add -f $REPO/release/src/router/bwdpi_source/asus/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/bwdpi_source/asus/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/asusnatnl/natnl/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/asd/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/amas-utils/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/ahs/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/acsd_arm/prebuilt/*
    git add -f $REPO/release/src/router/aaews/prebuild/*
    git add -f $REPO/release/src/router/dsl_drv_tool/*
    git add -f $REPO/release/src/router/spectrum/*
    git add -f $REPO/release/src/router/asuswebstorage/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/dropbox_client/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/ftpclient/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/libasc/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/libasuslog/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/libbcm/prebuilt/DSL-AC68U/*
    git add -f $REPO/release/src/router/libupnp_arm/*
    git add -f $REPO/release/src/router/nas_arm/nas/prebuilt/*
    git add -f $REPO/release/src/router/webdav_client/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src/router/wlc_nt/prebuild/DSL-AC68U/*
    git add -f $REPO/release/src-rt-6.x.4708/tc_fw/*
    
else
    echo "Unrecognized BUILD_NAME!"
    exit
fi



