#
# Broadcom SDK 6.37 ARM platform
#
NONE-OOKLA := OOKLA=y

export RT-AC68U_BASE := IPV6SUPP=y HTTPS=y ARM=y AUTODICT=y BBEXTRAS=y USBEXTRAS=y EBTABLES=y \
			SAMBA3=3.6.x MEDIASRV=y MODEM=y PARENTAL2=y ACCEL_PPTPD=y PRINTER=y STAINFO=y \
			WEBDAV=y USB="USB" GRO=y APP="network" PROXYSTA=y NOTIFICATION_CENTER=y HD_SPINDOWN=y \
			SMARTSYNCBASE=y SYSSTATE=y NATNL_AICLOUD=y NATNL_AIHOME=y SW_HW_AUTH=y BCM4708=y \
			DNSMQ=y SHP=y NVRAM_64K=y RTAC68U=y BCMWL6=y BCMWL6A=y EXT4FS=y BCM5301X=y DISK_MONITOR=y \
			BTN_WIFITOG=y LOGO_LED=y OPTIMIZE_XBOX=y ODMPID=y LED_BTN=y ROG=y EMAIL=y FRS_FEEDBACK=n \
			BCMSMP=y XHCI=y SSH=y NFS=y OPENVPN=y NEW_USER_LOW_RSSI=y AMAS=y WL_SCHED_V3=y GAME_MODE=y \
			TIMEMACHINE=y MDNS=y VPNC=y BRCM_NAND_JFFS2=y JFFS2LOG=y BCMFA=y BWDPI=y HSPOT=y \
			DUMP_OOPS_MSG=y LINUX_MTD="64" BCM7=n TEMPROOTFS=y DEBUGFS=y SNMPD=y TOR=y \
			MULTICASTIPTV=y FRR=y BCM_RECVFILE=y LAN50=y ATCOVER=y GETREALIP=y LETSENCRYPT=y UTF8_SSID=y \
			BCM5301X_TRAFFIC_MONITOR=y CLOUDCHECK=n REBOOT_SCHEDULE=y DPSTA=y DWB=y ETHOBD=y \
			CONNDIAG=y FORCE_AUTO_UPGRADE=n FORCE_ROAMING=y BCN_RPT=y BTM_11V=y OOKLA=y FILEFLEX=y \
			TFAT=y HFS="tuxera" NTFS="tuxera" REPEATER=y DUALWAN=y UPNPIGD2=n \
			NANO=y NTPD=y NETOOL=y TRACEROUTE=n

export RT-AC68U := $(RT-AC68U_BASE) FAKEHDR=y FORCE_SN=386 FORCE_EN=40000
export RT-AC68U += BUILD_NAME="RT-AC68U" NEWSSID_REV2=y UUPLUGIN=y AVBLCHAN=y ASUSCTRL=y \
		   AHS=n ASD=y FRS_LIVE_UPDATE=n OPEN_NAT=y SW_CTRL_ALLLED=y NVRAM_ENCRYPT=y
export RT-AC68U += JFFS_NVRAM=y OCNVC=y

DSL-AC68U-NONE := LOGO_LED=y LED_BTN=y ROG=y DNSPRIVACY=y MEDIASRV=y EMAIL=y DWB=y ETHOBD=y PRINTER=y ACCEL_PPTPD=y SMARTSYNCBASE=y CONNDIAG=y \
		  NATNL_AICLOUD=y NATNL_AIHOME=y OPTIMIZE_XBOX=y GAME_MODE=y TIMEMACHINE=y FORCE_ROAMING=y BCN_RPT=y BTM_11V=y \
		  HSPOT=y SNMPD=y TOR=y MULTICASTIPTV=y OOKLA=y FILEFLEX=y REPEATER=y NANO=y NEW_USER_LOW_RSSI=y AMAS=y
export DSL-AC68U := $(filter-out $(DSL-AC68U-NONE),$(RT-AC68U_BASE))
export DSL-AC68U += BUILD_NAME="DSL-AC68U" TFAT=y NTFS="tuxera" HFS="tuxera" DSL=y DSL_TCLINUX=y VDSL=y BTN_WPS_ALLLED=y TCPDUMP=n BCM4352_5G=y JFFS_NVRAM=y AHS=y ASD=n FRS_LIVE_UPDATE=y \
		    MERLINUPDATE=n WIFIPWR=y CONNTRACK=y CFGSYNC=n LIBASUSLOG=y TRACEROUTE=y HTOP=y CLOUDSYNC=n FRS_FEEDBACK=y OPENCONNECT=y LLDPD_1_0_11=y \
		    IPSEC=STRONGSWAN #IPSEC_SRVCLI_ONLY=CLI
export DSL-AC68U += DSL_REMOTE=y MULTISERVICE_WAN=y VAR_NVRAM=y
export DSL-AC68U += PC_SCHED_V3=n OPEN_NAT=y WIREGUARD=y
